backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "people"
    label: "People"
    folder: "src/pages/people"
    create: true
    slug: "{{name}}"
    label_singular: "Person"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "person"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Photo", name: "photo", widget: image, required: false}

  - name: "conversations"
    label: "Conversations"
    folder: "src/pages/conversations"
    create: true
    slug: "{{conversation}}"
    label_singular: "Conversation"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "conversation"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Audio URL", name: "audioURL", widget: "string"}
      - {label: "Photo", name: "photo", widget: image, required: false}
      - {label: "Participants", name: "participants", widget: relation, collection: "people", multiple: true, displayFields: ["name"], valueField: "name", searchFields: ["name"]}

